name: example
description: A new Flutter project.


publish_to: 'none' 

version: 1.0.0+1

environment:
  sdk: '>=2.19.1 <3.0.0'

dependencies:
  cupertino_icons: ^1.0.2
  flutter:
    sdk: flutter

  flutter_localizations:
    sdk: flutter
    
  localization_mapper_annotation:
    path: ../localization_mapper_annotation/

dev_dependencies:
  build_runner: ^2.3.3
  flutter_lints: ^2.0.0
  flutter_test:
    sdk: flutter

  localization_mapper_generator:
    path: ../localization_mapper_generator/

flutter:
  uses-material-design: true
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
