name: example
description: A new Flutter project.
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.0.0-0 <4.0.0'

dependencies:
  cupertino_icons: ^1.0.2
  flutter:
    sdk: flutter

  flutter_localizations:
    sdk: flutter
  intl: 0.18.1
  localization_mapper_annotation: 
    path: ../localization_mapper_annotation
  # localization_mapper_annotation: ^0.0.2

dev_dependencies:
  build_runner: ^2.3.3
  flutter_lints: ^2.0.0
  flutter_test:
    sdk: flutter
  localization_mapper_generator: 
    path: ../localization_mapper_generator
  # localization_mapper_generator: ^0.0.3

flutter:
  uses-material-design: true
